#!/usr/bin/env python3
"""Builds apps-script/webapp/index.html: the calculator as ONE file for a Google Apps Script web app.

Every local <script src="x.js"> is inlined (Apps Script HTML files cannot load sibling files), and
gas-bridge.js is placed first so the page reaches WebApp.gs through google.script.run.
Run from anywhere:  python3 trs398-calculator/apps-script/build_webapp.py
"""
import os, re

HERE = os.path.dirname(os.path.abspath(__file__))
APP = os.path.dirname(HERE)
OUT = os.path.join(HERE, 'webapp', 'index.html')

def read(name):
    with open(os.path.join(APP, name), encoding='utf-8') as f:
        return f.read()

def inline(name):
    code = read(name)
    if '</script' in code.lower():
        raise SystemExit(name + ' contains </script and cannot be inlined')
    return '<script>\n/* ---- ' + name + ' ---- */\n' + code.rstrip() + '\n</script>'

html = read('index.html')
local = re.compile(r'<script src="([\w.-]+\.js)"></script>')
names = local.findall(html)
if not names:
    raise SystemExit('no local scripts found in index.html')
first = True
def repl(m):
    global first
    block = inline(m.group(1))
    if first:   # the bridge must exist before any script asks for window.claude
        block = inline('gas-bridge.js') + '\n' + block
        first = False
    return block
html = local.sub(repl, html)
html = html.replace('<!doctype html>', '<!doctype html>\n<!-- Generated by apps-script/build_webapp.py from index.html — edit the sources, then rebuild. -->', 1)
os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, 'w', encoding='utf-8') as f:
    f.write(html)
print('wrote', OUT, len(html.encode('utf-8')), 'bytes; inlined', ['gas-bridge.js'] + names)
